version: "3.9"
services:
  mysql:
    image: "mysql:5.7.34"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-secret-pw
    healthcheck:
      test: "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 5s
      retries: 50
  web:
    image: "docker.io/library/app:1.0.0"
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root-secret-pw
    depends_on:
      mysql:
        condition: service_healthy
